sudo: false

language: node_js

node_js:
  - '4.2'

# services:
  # - mongodb

# cache:
  # directories:
    # - node_modules
    # - bower_components

notifications:
  email:
    - marc.perrinpelletier@gmail.com

# before_install:
  # - npm install -g npm@latest

# before_script:
  # - export DISPLAY=:99.0
  # - export TNU_ROOT_DIRECTORY=/home/travis/build/theodo/pepiniere-dashbook
  # - mkdir -p log/node-app
  # - sh -e /etc/init.d/xvfb start
  # - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  # - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  # - sudo apt-get update
  # - sudo apt-get install -y mongodb-org=2.6.10 mongodb-org-server=2.6.10 mongodb-org-shell=2.6.10 mongodb-org-mongos=2.6.10 mongodb-org-tools=2.6.10
  # - sleep 15 #mongo may not be responded directly. See http://docs.travis-ci.com/user/database-setup/#MongoDB
  # - mongo --version

script:
  - npm test
