dev-server:
  build: .
  dockerfile: Dockerfile.dev
  volumes:
    - .:/var/www/stbk
  # command: bash -c "npm install && ./node_modules/.bin/bower install && ./node_modules/.bin/sails lift"
  # command: bash -c "npm install && ./node_modules/.bin/sails lift"
  command: bash -c "npm install && ./node_modules/.bin/coffee app.coffee"
  # ports: prevents from scaling. Expose is better in this case because it only makes the port accessible to linked containers
  # ports:
    # - '1337:1337'
  # use ports instead to test api in browser
  expose:
    - 1337
  links:
    - dev-database

dev-database:
  image: mongo:latest
  command: mongod --smallfiles
  # volumes:
    # - ./mongo:/data/db

# dev-lb:
  # image: tutum/haproxy:latest
  # links:
    # - dev-server
  # ports:
   # - '8080:80'

dev-proxy:
  image: nginx:latest
  ports:
    # - '80:8080'
    - '5013:5013'
  links:
    - dev-server
  volumes:
    - ./devops/proxy/streambacker.dev.conf:/etc/nginx/conf.d/streambacker.dev.conf
  volumes_from:
    - dev-server
