# web:
  # build: .
  # ports:
    # - '5000:5000'
vendors:
  image: node:0.10
  working_dir: /app
  volumes:
    - .:/app
  command: npm install
  links:
    - mongo
  # env_file: .env

mongo:
  image: mongo:latest
  volumes:
    - ./mongo:/data/db

proxy:
  image: nginx:1.7
  ports:
    - '5013:5013'
  volumes:
    - devops/proxy:/etc/nginx/conf.d
    - www:/var/www
