server:
  # image: node:latest
  build: .
  # dockerfile: Dockerfile.dev.server
  # working_dir: /home/stbk
  # working_dir: /var/www/stbk
  volumes:
    - .:/var/www/stbk
    # - .:/home/stbk
    # - .:/stbk-app
  # command: bash -c "npm install && ./node_modules/.bin/bower install && ./node_modules/.bin/sails lift"
  command: bash -c "npm install && ./node_modules/.bin/sails lift"
  # command: bash
  # command: ./node_modules/.bin/sails lift
  ports:
    - '1337:1337'
  links:
    - stbkmongo

stbkmongo:
  image: mongo:latest
  command: mongod --smallfiles
  # volumes:
    # - ./mongo:/data/db

proxy:
  image: nginx:latest
  # image: nginx:1.7
  # build: .
  # user: root
  # dockerfile: Dockerfile.dev.proxy
  # working_dir: /home/stbk
  ports:
    - '5013:5013'
    # - '8080:8080'
    # - '1337:1337'
  links:
    - server
  volumes:
    # - ./www:/home/stbk/www
    # - ./www:/var/www/stbk/www
    - ./web:/var/www/stbk/web
    # - .:/var/www/stbk
    - ./devops/proxy:/etc/nginx/conf.d
