# web:
  # build: .
  # ports:
    # - '5000:5000'
server: &defaults
  # build: .
  image: node:0.10
  working_dir: /app
  volumes:
    - .:/app
  command: ./node_modules/.bin/coffee server/server.coffee
  links:
    - mongo

npm:
  <<: *defaults
  entrypoint: ['npm']

mongo:
  image: mongo:latest
  volumes:
    - ./mongo:/data/db

proxy:
  image: nginx:1.7
  ports:
    - '5013:5013'
  volumes:
    - devops/proxy:/etc/nginx/conf.d
    - www:/var/www
