prod-server:
  image: marcpepe/streambacker-server-automated:latest
  ports:
    - '1337:1337'
  links:
    - prod-database

prod-database:
  image: mongo:latest
  command: mongod --smallfiles

prod-proxy:
  image: marcpepe/streambacker-proxy-automated:latest
  ports:
    - '5013:5013'
  links:
    - prod-server
  volumes_from:
    - prod-server
