server:
  build: .
  links:
    - stbkmongo

stbkmongo:
  image: mongo:latest
  command: mongod --smallfiles

proxy:
  image: nginx:latest
  ports:
    - '5013:5013'
  volumes:
    - ./devops/proxy:/etc/nginx/conf.d
    - ./www:/var/www
  links:
    - server
